"use client";

import { use, useEffect, useState } from "react";
import { ArrowLeft, MessageCircle, Users } from "lucide-react";
import { WorkspaceShell } from "@/components/workspace-shell";

type Community = { id: string; name: string; description: string | null; type: string; status: string; state: { name: string } | null; localGovernment: { name: string } | null; ward: { name: string } | null; pollingUnit: { name: string } | null; _count: { members: number } };
type Member = { joinedAt: string; membership: { id: string; firstName: string; lastName: string; email: string | null; phone: string | null; whatsappNumber: string | null; status: string } };
const apiUrl = (() => {
  const raw = process.env.NEXT_PUBLIC_API_URL ?? "https://api.peoplesfirstmovement.com";
  const normalized = raw.replace(/\/+$/, "");
  return normalized.endsWith("/api") ? normalized : `${normalized}/api`;
})();

export default function CommunityDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [community, setCommunity] = useState<Community | null>(null); const [members, setMembers] = useState<Member[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const token = localStorage.getItem("pfm.accessToken"); if (!token) { window.location.href = "/login"; return; } Promise.all([fetch(`${apiUrl}/v1/communities/${id}`, { headers: { Authorization: `Bearer ${token}` } }), fetch(`${apiUrl}/v1/communities/${id}/members`, { headers: { Authorization: `Bearer ${token}` } })]).then(async ([communityResponse, membersResponse]) => { const communityBody: unknown = await communityResponse.json(); const membersBody: unknown = await membersResponse.json(); if (!communityResponse.ok || !membersResponse.ok || !Array.isArray(membersBody)) throw new Error("Unable to load community"); setCommunity(communityBody as Community); return membersBody as Member[]; }).then(setMembers).catch((requestError: unknown) => setError(requestError instanceof Error ? requestError.message : "Unable to load community")).finally(() => setLoading(false)); }, [id]);
  const location = community?.pollingUnit?.name ?? community?.ward?.name ?? community?.localGovernment?.name ?? community?.state?.name ?? "Organization geography";
  return <WorkspaceShell title={community?.name ?? "Community"} subtitle={`${location} • ${community?._count.members ?? members.length} members`}><section className="panel page-panel"><div className="community-tabs"><a className="secondary-button" href="/communities"><ArrowLeft size={15} />Communities</a><a className="primary-button" href="/messages"><MessageCircle size={15} />Chat</a><span className="status-badge"><Users size={15} />{community?._count.members ?? members.length} members</span></div><div className="panel-heading"><div><h2>{community?.name ?? "Community"}</h2><p>{community?.description ?? "Geographic community workspace"}</p></div><span className="status-badge">{community?.type ?? ""}</span></div>{loading ? <div className="loading-state">Loading community...</div> : error ? <div className="error-state"><strong>{error}</strong></div> : members.length === 0 ? <div className="empty-state"><h2>No members assigned</h2><p>Members are enrolled automatically from their geographic assignment.</p></div> : <div className="member-table-wrap"><table className="member-table"><thead><tr><th>Member</th><th>Contact</th><th>Status</th></tr></thead><tbody>{members.map(({ membership }) => <tr key={membership.id}><td><strong>{membership.firstName} {membership.lastName}</strong><small>{membership.email ?? "No email"}</small></td><td><strong>{membership.phone ?? "No phone"}</strong><small>{membership.whatsappNumber ?? "No WhatsApp"}</small></td><td><span className={`member-status ${membership.status.toLowerCase()}`}>{membership.status}</span></td></tr>)}</tbody></table></div>}</section></WorkspaceShell>;
}